version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    restart: always
    container_name: $DB_CONTAINER_NAME
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - gps_db:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - mynetwork


networks:
  mynetwork:

volumes:
  gps_db:
